version: '3.1'
services:
  stats-server:
    build: ./stats-server/service
    image: explore-stats-server-image
    container_name: explore-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - EXPLORE_MAIN_URL=http://main:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main-explore
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    volumes:
    - /var/lib/postgresql/data/
    container_name: main-db
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=main-explore
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root