version: '3.1'
services:
  stats-server:
    build: stats-service/service
    image: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - EXPLORE_MAIN_URL=http://main:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-server-explore

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: stats_db
    ports:
      - "9091:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
